//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosOperaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_LineasMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_LineasMO()
        {
            this.wh_LotesMO = new HashSet<wh_LotesMO>();
        }
    
        public long Id { get; set; }
        public string Status { get; set; }
        public string Line { get; set; }
        public string Item { get; set; }
        public string Rev { get; set; }
        public string SrcLocator { get; set; }
        public string SrcUbicacion { get; set; }
        public string DestLocator { get; set; }
        public string DestUbicacion { get; set; }
        public string Requester { get; set; }
        public string Ref { get; set; }
        public string UoM { get; set; }
        public string Qty { get; set; }
        public string Asterisk { get; set; }
        public int wh_moveorder_Id { get; set; }
    
        public virtual wh_moveorder wh_moveorder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_LotesMO> wh_LotesMO { get; set; }
    }
}
