//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosOperaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_masterskus
    {
        public int Id { get; set; }
        public Nullable<int> PiezasPorCaja { get; set; }
        public Nullable<int> CajasPorCama { get; set; }
        public Nullable<int> PiezasPorTarima { get; set; }
        public int skus_id { get; set; }
    }
}
