//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosOperaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_molines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_molines()
        {
            this.wh_molinesdetalles = new HashSet<wh_molinesdetalles>();
        }
    
        public int Id { get; set; }
        public string NumOrder { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int Empleados_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_molinesdetalles> wh_molinesdetalles { get; set; }
    }
}
