//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosOperaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_moveorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_moveorder()
        {
            this.wh_LineasMO = new HashSet<wh_LineasMO>();
        }
    
        public int Id { get; set; }
        public string NumOrder { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public int wh_statusmo_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_LineasMO> wh_LineasMO { get; set; }
        public virtual wh_statusmo wh_statusmo { get; set; }
    }
}
