//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosEscaneos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hd_ordenes()
        {
            this.hd_codigosqr = new HashSet<hd_codigosqr>();
            this.hd_detordenesskus = new HashSet<hd_detordenesskus>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string NumeroOrden { get; set; }
        public string OracleID { get; set; }
        public string Guia { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public string Observaciones { get; set; }
        public int Pickers_Id { get; set; }
        public int Auditores_Id { get; set; }
        public int Empleados_Id { get; set; }
        public int hd_statusorden_Id { get; set; }
        public int hd_statusquickship_Id { get; set; }
    
        public virtual auditores auditores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hd_codigosqr> hd_codigosqr { get; set; }
        public virtual hd_statusorden hd_statusorden { get; set; }
        public virtual hd_statusquickship hd_statusquickship { get; set; }
        public virtual pickers pickers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hd_detordenesskus> hd_detordenesskus { get; set; }
    }
}
