//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosEscaneos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_skushomedelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hd_skushomedelivery()
        {
            this.hd_detordenesskus = new HashSet<hd_detordenesskus>();
        }
    
        public long Id { get; set; }
        public Nullable<bool> QtyManual { get; set; }
        public Nullable<bool> QRCode { get; set; }
        public int skus_Id { get; set; }
    
        public virtual skus skus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hd_detordenesskus> hd_detordenesskus { get; set; }
    }
}
