//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosArzys
{
    using System;
    using System.Collections.Generic;
    
    public partial class arz_detunidadretrabajo
    {
        public int Id { get; set; }
        public int arz_unidades_Id { get; set; }
        public int arz_retrabajos_Id { get; set; }
    
        public virtual arz_retrabajos arz_retrabajos { get; set; }
        public virtual arz_unidades arz_unidades { get; set; }
    }
}
