//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosArzys
{
    using System;
    using System.Collections.Generic;
    
    public partial class arz_unidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arz_unidades()
        {
            this.arz_detunidadproceso = new HashSet<arz_detunidadproceso>();
            this.arz_detunidadretrabajo = new HashSet<arz_detunidadretrabajo>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaHoraAlta { get; set; }
        public string Economico { get; set; }
        public Nullable<System.DateTime> CitaArribo { get; set; }
        public Nullable<System.DateTime> CitaDestino { get; set; }
        public int arz_lineatransporte_Id { get; set; }
        public int arz_destinos_Id { get; set; }
        public int arz_statusunidad_Id { get; set; }
    
        public virtual arz_destinos arz_destinos { get; set; }
        public virtual arz_lineatransporte arz_lineatransporte { get; set; }
        public virtual arz_statusunidad arz_statusunidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arz_detunidadproceso> arz_detunidadproceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arz_detunidadretrabajo> arz_detunidadretrabajo { get; set; }
    }
}
